In [4]:
# Fundamentals of Tensor Operations with PyTorch and NumPy

import torch
import numpy as np

print("PyTorch version:", torch.__version__)
print("NumPy version:", np.__version__)

PyTorch version: 2.10.0
NumPy version: 2.4.1


In [5]:
# 1. Creating 1D, 2D, 3D tensors (PyTorch) and arrays (NumPy)

# 1D
pt_1d = torch.tensor([1, 2, 3])
np_1d = np.array([1, 2, 3])

# 2D
pt_2d = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
np_2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

# 3D
pt_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
np_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("PyTorch 1D:", pt_1d, pt_1d.shape)
print("NumPy   1D:", np_1d, np_1d.shape)
print("PyTorch 2D:\n", pt_2d, pt_2d.shape)
print("NumPy   2D:\n", np_2d, np_2d.shape)
print("PyTorch 3D:\n", pt_3d, pt_3d.shape)
print("NumPy   3D:\n", np_3d, np_3d.shape)

PyTorch 1D: tensor([1, 2, 3]) torch.Size([3])
NumPy   1D: [1 2 3] (3,)
PyTorch 2D:
 tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
NumPy   2D:
 [[1 2 3]
 [4 5 6]] (2, 3)
PyTorch 3D:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) torch.Size([2, 2, 2])
NumPy   3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


In [6]:
# 2. Element-wise operations

pt_a = torch.tensor([1., 2., 3.])
pt_b = torch.tensor([4., 5., 6.])
np_a = np.array([1., 2., 3.])
np_b = np.array([4., 5., 6.])

print("PyTorch add:", pt_a + pt_b)
print("NumPy   add:", np_a + np_b)

print("PyTorch mul:", pt_a * pt_b)
print("NumPy   mul:", np_a * np_b)

print("PyTorch sin:", torch.sin(pt_a))
print("NumPy   sin:", np.sin(np_a))

PyTorch add: tensor([5., 7., 9.])
NumPy   add: [5. 7. 9.]
PyTorch mul: tensor([ 4., 10., 18.])
NumPy   mul: [ 4. 10. 18.]
PyTorch sin: tensor([0.8415, 0.9093, 0.1411])
NumPy   sin: [0.84147098 0.90929743 0.14112001]


In [7]:
# 3. Indexing, slicing, and boolean masking

pt_x = torch.tensor([[10, 11, 12],
                     [13, 14, 15]])
np_x = np.array([[10, 11, 12],
                 [13, 14, 15]])

print("PyTorch single element:", pt_x[0, 1])
print("NumPy   single element:", np_x[0, 1])

print("PyTorch row slice:", pt_x[0])
print("NumPy   row slice:", np_x[0])

print("PyTorch column slice:", pt_x[:, 1])
print("NumPy   column slice:", np_x[:, 1])

print("PyTorch sub-tensor:\n", pt_x[:, 1:])
print("NumPy   sub-array:\n", np_x[:, 1:])

pt_mask = pt_x > 12
np_mask = np_x > 12

print("PyTorch mask:\n", pt_mask)
print("NumPy   mask:\n", np_mask)

print("PyTorch values > 12:", pt_x[pt_mask])
print("NumPy   values > 12:", np_x[np_mask])

PyTorch single element: tensor(11)
NumPy   single element: 11
PyTorch row slice: tensor([10, 11, 12])
NumPy   row slice: [10 11 12]
PyTorch column slice: tensor([11, 14])
NumPy   column slice: [11 14]
PyTorch sub-tensor:
 tensor([[11, 12],
        [14, 15]])
NumPy   sub-array:
 [[11 12]
 [14 15]]
PyTorch mask:
 tensor([[False, False, False],
        [ True,  True,  True]])
NumPy   mask:
 [[False False False]
 [ True  True  True]]
PyTorch values > 12: tensor([13, 14, 15])
NumPy   values > 12: [13 14 15]


In [8]:
# 4. Shape transformations: view, reshape, unsqueeze, squeeze

# PyTorch view vs reshape
pt_y = torch.arange(6)  # [0, 1, 2, 3, 4, 5]
print("Original pt_y:", pt_y, pt_y.shape)

pt_y_view = pt_y.view(2, 3)
pt_y_reshape = pt_y.reshape(2, 3)
print("pt_y.view(2, 3):\n", pt_y_view, pt_y_view.shape)
print("pt_y.reshape(2, 3):\n", pt_y_reshape, pt_y_reshape.shape)

# NumPy reshape
np_y = np.arange(6)
np_y_reshape = np_y.reshape(2, 3)
print("np_y:", np_y, np_y.shape)
print("np_y.reshape(2, 3):\n", np_y_reshape, np_y_reshape.shape)

# unsqueeze / squeeze in PyTorch and equivalents in NumPy
pt_z = torch.tensor([1, 2, 3])
print("pt_z:", pt_z, pt_z.shape)

pt_z_unsq0 = pt_z.unsqueeze(0)
pt_z_unsq1 = pt_z.unsqueeze(1)
print("pt_z.unsqueeze(0):", pt_z_unsq0, pt_z_unsq0.shape)
print("pt_z.unsqueeze(1):\n", pt_z_unsq1, pt_z_unsq1.shape)

pt_z_sq = pt_z_unsq1.squeeze()
print("pt_z_unsq1.squeeze():", pt_z_sq, pt_z_sq.shape)

np_z = np.array([1, 2, 3])
np_z_unsq0 = np.expand_dims(np_z, axis=0)
np_z_unsq1 = np.expand_dims(np_z, axis=1)
print("np_z:", np_z, np_z.shape)
print("np.expand_dims(np_z, 0):", np_z_unsq0, np_z_unsq0.shape)
print("np.expand_dims(np_z, 1):\n", np_z_unsq1, np_z_unsq1.shape)

np_z_sq = np.squeeze(np_z_unsq1)
print("np.squeeze(np_z_unsq1):", np_z_sq, np_z_sq.shape)

Original pt_y: tensor([0, 1, 2, 3, 4, 5]) torch.Size([6])
pt_y.view(2, 3):
 tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3])
pt_y.reshape(2, 3):
 tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3])
np_y: [0 1 2 3 4 5] (6,)
np_y.reshape(2, 3):
 [[0 1 2]
 [3 4 5]] (2, 3)
pt_z: tensor([1, 2, 3]) torch.Size([3])
pt_z.unsqueeze(0): tensor([[1, 2, 3]]) torch.Size([1, 3])
pt_z.unsqueeze(1):
 tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])
pt_z_unsq1.squeeze(): tensor([1, 2, 3]) torch.Size([3])
np_z: [1 2 3] (3,)
np.expand_dims(np_z, 0): [[1 2 3]] (1, 3)
np.expand_dims(np_z, 1):
 [[1]
 [2]
 [3]] (3, 1)
np.squeeze(np_z_unsq1): [1 2 3] (3,)


In [9]:
# 5. Broadcasting

# Broadcasting a (2, 3) with (3,) in PyTorch and NumPy
pt_A = torch.ones(2, 3)
pt_b = torch.tensor([1., 2., 3.])

np_A = np.ones((2, 3))
np_b = np.array([1., 2., 3.])

print("pt_A shape:", pt_A.shape, "pt_b shape:", pt_b.shape)
print("pt_A + pt_b:\n", pt_A + pt_b)

print("np_A shape:", np_A.shape, "np_b shape:", np_b.shape)
print("np_A + np_b:\n", np_A + np_b)

# Another example: (3, 1) and (1, 4)
pt_C = torch.arange(3).float().unsqueeze(1)  # (3, 1)
pt_D = torch.arange(4).float().unsqueeze(0)  # (1, 4)

print("pt_C shape:", pt_C.shape, "pt_D shape:", pt_D.shape)
print("pt_C + pt_D (broadcasted to (3, 4)):\n", pt_C + pt_D)

np_C = np.arange(3).reshape(3, 1).astype(float)
np_D = np.arange(4).reshape(1, 4).astype(float)

print("np_C shape:", np_C.shape, "np_D shape:", np_D.shape)
print("np_C + np_D (broadcasted to (3, 4)):\n", np_C + np_D)

pt_A shape: torch.Size([2, 3]) pt_b shape: torch.Size([3])
pt_A + pt_b:
 tensor([[2., 3., 4.],
        [2., 3., 4.]])
np_A shape: (2, 3) np_b shape: (3,)
np_A + np_b:
 [[2. 3. 4.]
 [2. 3. 4.]]
pt_C shape: torch.Size([3, 1]) pt_D shape: torch.Size([1, 4])
pt_C + pt_D (broadcasted to (3, 4)):
 tensor([[0., 1., 2., 3.],
        [1., 2., 3., 4.],
        [2., 3., 4., 5.]])
np_C shape: (3, 1) np_D shape: (1, 4)
np_C + np_D (broadcasted to (3, 4)):
 [[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]


In [10]:
# 6. In-place vs out-of-place operations (PyTorch vs NumPy)

# PyTorch
pt_w = torch.tensor([1., 2., 3.])
print("Original pt_w:", pt_w)

# Out-of-place: pt_w unchanged
pt_w_out = pt_w + 1
print("pt_w + 1 (out-of-place):", pt_w_out)
print("pt_w after out-of-place:", pt_w)

# In-place: modifies pt_w
pt_w.add_(1)
print("pt_w after add_(1) (in-place):", pt_w)

# NumPy
np_w = np.array([1., 2., 3.])
print("\nOriginal np_w:", np_w)

# Out-of-place
np_w_out = np_w + 1
print("np_w + 1 (out-of-place):", np_w_out)
print("np_w after out-of-place:", np_w)

# In-place using +=
np_w += 1
print("np_w after += 1 (in-place):", np_w)

print("\nNote: In PyTorch, in-place ops usually have a trailing underscore (e.g., add_, mul_).\n" "They can save memory but must be used carefully with autograd.")

Original pt_w: tensor([1., 2., 3.])
pt_w + 1 (out-of-place): tensor([2., 3., 4.])
pt_w after out-of-place: tensor([1., 2., 3.])
pt_w after add_(1) (in-place): tensor([2., 3., 4.])

Original np_w: [1. 2. 3.]
np_w + 1 (out-of-place): [2. 3. 4.]
np_w after out-of-place: [1. 2. 3.]
np_w after += 1 (in-place): [2. 3. 4.]

Note: In PyTorch, in-place ops usually have a trailing underscore (e.g., add_, mul_).
They can save memory but must be used carefully with autograd.
